# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
