# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170729_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='blog/media/Capture.PNG', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.CharField(default='blog/media/robotics.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
