# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170729_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=20)),
                ('descriptions', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('current', models.BooleanField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
