# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.AdSlots'),
        ),
    ]
