# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170704_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdSlots',
            new_name='AdSlot',
        ),
    ]
