# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170704_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='static/blog/images'),
        ),
    ]
