# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_newsletteremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
