# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170704_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='blog/static/blog/images'),
        ),
    ]
