# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170730_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer_name',
        ),
        migrations.AlterField(
            model_name='review',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
