# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170704_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/static/blog/images'),
        ),
    ]
