# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170803_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
