# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170713_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='review',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
