# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django_boto.s3.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170805_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(storage=django_boto.s3.storage.S3Storage(), upload_to='ads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django_boto.s3.storage.S3Storage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, storage=django_boto.s3.storage.S3Storage(), upload_to='images'),
        ),
    ]
