# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170717_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=10),
        ),
    ]
