# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170717_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
