# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170719_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='review'),
        ),
    ]
