# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:07
from __future__ import unicode_literals

from django.db import migrations
import django_boto.s3.storage
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170805_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(storage=django_boto.s3.storage.S3Storage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, storage=django_boto.s3.storage.S3Storage(), upload_to='images'),
        ),
    ]
