# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_review_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
