# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170808_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Default description'),
        ),
    ]
