# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170722_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 22, 19, 7, 13, 304433), editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 22, 19, 7, 13, 304433)),
        ),
    ]
