# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_boto.s3.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170809_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django_boto.s3.storage.S3Storage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, storage=django_boto.s3.storage.S3Storage(), upload_to='images'),
        ),
    ]
