# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20170819_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_compressed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
