# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_review_image_compressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_compressed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
