# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20170820_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_compressed',
            field=models.BooleanField(default=False),
        ),
    ]
