# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20170821_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image_compressed',
        ),
    ]
