# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_boto.s3.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_remove_review_image_compressed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django_boto.s3.storage.S3Storage(), upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Review'),
        ),
    ]
