# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20170822_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
