# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_reviewimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='name',
            field=models.CharField(default='reviewimage', max_length=50),
        ),
    ]
