# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_reviewimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
