# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_review_image_thumb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='slug',
        ),
        migrations.AlterField(
            model_name='review',
            name='image_thumb_url',
            field=models.URLField(blank=True),
        ),
    ]
