# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20170824_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.AlterField(
            model_name='product',
            name='links',
            field=models.TextField(),
        ),
    ]
