# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20170824_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Product'),
        ),
    ]
