# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_promotion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
