# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20170825_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='link',
        ),
    ]
