# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20170825_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=5, editable=False),
        ),
    ]
