# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blog', '0050_auto_20170827_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
