# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_review_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='site',
        ),
    ]
