# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_remove_review_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateField(null=True),
        ),
    ]
