# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_product_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
