# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20170827_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
