# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20170901_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='overall_verdict',
            field=models.TextField(blank=True),
        ),
    ]
