# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_auto_20170902_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modified',
            new_name='created',
        ),
    ]
