# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_auto_20170903_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='modified',
        ),
    ]
