# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_remove_review_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_compressed',
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
