# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_auto_20170908_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_compressed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
